//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyOrganizer.Properties {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MoneyOrganizer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Byte[].
        /// </summary>
        internal static byte[] Automotive {
            get {
                object obj = ResourceManager.GetObject("Automotive", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Byte[].
        /// </summary>
        internal static byte[] Beauty {
            get {
                object obj = ResourceManager.GetObject("Beauty", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Byte[].
        /// </summary>
        internal static byte[] Clothes {
            get {
                object obj = ResourceManager.GetObject("Clothes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Byte[].
        /// </summary>
        internal static byte[] DIY {
            get {
                object obj = ResourceManager.GetObject("DIY", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Byte[].
        /// </summary>
        internal static byte[] Electronics {
            get {
                object obj = ResourceManager.GetObject("Electronics", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Byte[].
        /// </summary>
        internal static byte[] Entertainment {
            get {
                object obj = ResourceManager.GetObject("Entertainment", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Byte[].
        /// </summary>
        internal static byte[] Garden {
            get {
                object obj = ResourceManager.GetObject("Garden", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Byte[].
        /// </summary>
        internal static byte[] Grocery {
            get {
                object obj = ResourceManager.GetObject("Grocery", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Byte[].
        /// </summary>
        internal static byte[] Health {
            get {
                object obj = ResourceManager.GetObject("Health", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Byte[].
        /// </summary>
        internal static byte[] Home {
            get {
                object obj = ResourceManager.GetObject("Home", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Byte[].
        /// </summary>
        internal static byte[] income {
            get {
                object obj = ResourceManager.GetObject("income", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Byte[].
        /// </summary>
        internal static byte[] logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Byte[].
        /// </summary>
        internal static byte[] Luxury {
            get {
                object obj = ResourceManager.GetObject("Luxury", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Byte[].
        /// </summary>
        internal static byte[] Others {
            get {
                object obj = ResourceManager.GetObject("Others", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Byte[].
        /// </summary>
        internal static byte[] outcome {
            get {
                object obj = ResourceManager.GetObject("outcome", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Byte[].
        /// </summary>
        internal static byte[] Software {
            get {
                object obj = ResourceManager.GetObject("Software", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Byte[].
        /// </summary>
        internal static byte[] Sport {
            get {
                object obj = ResourceManager.GetObject("Sport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Byte[].
        /// </summary>
        internal static byte[] tgBtn {
            get {
                object obj = ResourceManager.GetObject("tgBtn", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Byte[].
        /// </summary>
        internal static byte[] Toys {
            get {
                object obj = ResourceManager.GetObject("Toys", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Byte[].
        /// </summary>
        internal static byte[] Transport {
            get {
                object obj = ResourceManager.GetObject("Transport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Byte[].
        /// </summary>
        internal static byte[] Travel {
            get {
                object obj = ResourceManager.GetObject("Travel", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
